language: ruby
rvm:
 - 2.3.4
 - jruby
 - rbx-2

services:
  - mysql

test:
 adapter: mysql2
 database: tutoria_test
 username: travis
 encoding: utf8

before_install:
 - mysql -e 'CREATE DATABASE tutoria_test;'

script:
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rake db:seed
 - bundle exec rake
